language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
- pip install coverage
- pip install coveralls
- pip install -r requirements.txt
script:
- cd test
- env PYTHONPATH=.. python -m unitest --verbose all
- cd ..
- env PYTHONPATH=. coverage run test/all.py
after_success:
- coveralls
